import type { NextPage } from "next";
import Image from "next/future/image";
import Head from "next/head";

import useBattleStore from "../state";

const Home: NextPage = () => {
  const { left, right, animate } = useBattleStore();

  const handleClick = () => {
    animate();
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-green-200">
        <button
          className="rounded-md bg-blue-400 px-5 py-3 font-bold text-white"
          onClick={handleClick}
        >
          Animate
        </button>
        <div className="grid w-full max-w-2xl grid-cols-battle">
          <div className="relative aspect-square">
            <Image
              src={`/images/${left.sprite}`}
              fill
              alt="Character"
              sizes="50vh"
            />
          </div>
          <div></div>
          <div className="relative aspect-square -scale-x-100">
            <Image
              src={`/images/${right.sprite}`}
              fill
              alt="Character"
              sizes="50vh"
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
